# Generated by Django 5.2.15 on 2026-06-24 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pesel', models.CharField(blank=True, max_length=11)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('identity_document', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('building_number', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(blank=True, max_length=20)),
                ('job_position', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='occupational_health.organization')),
            ],
        ),
    ]
