# Generated by Django 5.2.15 on 2026-06-24 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PHYSICAL', 'Czynniki fizyczne'), ('DUST', 'Pyly'), ('CHEMICAL', 'Czynniki chemiczne'), ('BIOLOGICAL', 'Czynniki biologiczne'), ('OTHER', 'Inne czynniki, w tym niebezpieczne i uciazliwe')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exposure_factors', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exposure_factors', to='occupational_health.organization')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
    ]
