# Generated by Django 5.2.15 on 2026-06-24 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0003_exposurefactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_type', models.CharField(choices=[('INITIAL', 'Wstepne'), ('PERIODIC', 'Okresowe'), ('CONTROL', 'Kontrolne')], max_length=20)),
                ('job_position', models.CharField(max_length=150)),
                ('work_description', models.TextField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('TO_ORDER', 'Do zlecenia'), ('ORDERED', 'Zlecone'), ('COMPLETED', 'Wykonane'), ('CANCELLED', 'Anulowane')], default='TO_ORDER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='occupational_health.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='occupational_health.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_position', models.CharField(max_length=150)),
                ('work_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_referral_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_templates', to='occupational_health.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReferralExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_description', models.TextField()),
                ('measurement_result', models.CharField(blank=True, max_length=255)),
                ('exposure_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_exposures', to='occupational_health.exposurefactor')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='occupational_health.referral')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('referral', 'exposure_factor'), name='unique_referral_exposure_factor')],
            },
        ),
        migrations.CreateModel(
            name='ReferralTemplateExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_description', models.TextField()),
                ('measurement_result', models.CharField(blank=True, max_length=255)),
                ('exposure_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_exposures', to='occupational_health.exposurefactor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='occupational_health.referraltemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'exposure_factor'), name='unique_referral_template_exposure_factor')],
            },
        ),
    ]
