# Generated by Django 5.2.15 on 2026-06-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0004_referral_referraltemplate_referralexposure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identity_document',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exposurefactor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='referral',
            name='work_description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='referralexposure',
            name='exposure_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='referralexposure',
            name='measurement_result',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='referraltemplate',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='referraltemplate',
            name='work_description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='referraltemplateexposure',
            name='exposure_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='referraltemplateexposure',
            name='measurement_result',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
