# Generated by Django 5.2.15 on 2026-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0005_alter_employee_identity_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposurefactor',
            name='category',
            field=models.CharField(
                choices=[
                    ('PHYSICAL', 'Czynniki fizyczne'),
                    ('DUST', 'Py\u0142y'),
                    ('CHEMICAL', 'Czynniki chemiczne'),
                    ('BIOLOGICAL', 'Czynniki biologiczne'),
                    (
                        'OTHER',
                        'Inne czynniki, w tym niebezpieczne i uci\u0105\u017cliwe',
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
